package de.sswis.view.CustomComponents;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Ein Panel, das eine Tabelle bestehend aus festgelegtem Text Labels und Text Eingabe Feldern.
 */
public class ParameterTable {

    private List<JLabel> parameterLabels;
    private List<JTextField> parameterTextFields;

    private JPanel MainPanel;
    private JLabel additionalParameterLabel;


    public ParameterTable(List<String> parameterNames) {
        parameterLabels = new ArrayList<JLabel>();
        parameterTextFields = new ArrayList<JTextField>();

        $$$setupUI$$$();
        for (int i = 0; i < parameterNames.size(); i++) {
            parameterLabels.add(new JLabel(parameterNames.get(i)));
            parameterTextFields.add(new JTextField());
        }
    }

    private void addParameterLines() {
        for (int i = 0; i < parameterLabels.size(); i++) {
            MainPanel.add(parameterLabels.get(i),
                    new GridConstraints(1 + i, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

            MainPanel.add(parameterTextFields.get(i),
                    new GridConstraints(1 + i, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));

        }
    }

    public List<String> getAllUserInputs() {
        ArrayList<String> parameterInput = new ArrayList<String>();
        for (int i = 0; i < parameterTextFields.size(); i++) {
            parameterInput.add(parameterTextFields.get(i).getText());
        }
        return parameterInput;
    }

    private void createUIComponents() {
        additionalParameterLabel = new JLabel();
        addParameterLines();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(20, 2, new Insets(0, 0, 0, 0), -1, -1));
        additionalParameterLabel.setText("zusätzliche Parameter:");
        MainPanel.add(additionalParameterLabel, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }
}
