package de.sswis.view.CustomComponents;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

/**
 * Ein Tab fuer ein Startkapital innerhalb einer Gruppe, der in der NewInitializationView angezeigt wird.
 * <p>
 * Dient zur Bestimmung der Höhe und der Agentenverteilung des Startkapitals.
 */
public class StartCapitalTab {

    private JPanel MainPanel;
    private String title;

    private JFormattedTextField startCapitalTextField;

    private ButtonGroup buttonGroup;
    private JRadioButton idAgentRadioButton;
    private JRadioButton percentageAgentRadioButton;
    private JLabel idLabel;
    private JFormattedTextField idAgentTextField;
    private JLabel percentageLabel;
    private JFormattedTextField percentageAgentTextField;

    public StartCapitalTab() {
        update();
    }

    public void update() {
        idLabel.setEnabled(idAgentRadioButton.isSelected());
        idAgentTextField.setEnabled(idAgentRadioButton.isSelected());

        percentageLabel.setEnabled(percentageAgentRadioButton.isSelected());
        percentageAgentTextField.setEnabled(percentageAgentRadioButton.isSelected());

        if (startCapitalTextField.getText() == null) {
            title = "?";
        } else  {
            title = startCapitalTextField.getText();
        }

        if (getAgentUserInput() == null) {
            title = "*" + title;
        }

    }

    public boolean isAgentIDsSelected() {
        return idAgentRadioButton.isSelected();
    }

    public String getTitle() {
        return title;
    }

    public String getStartCapital() {
        return startCapitalTextField.getText();
    }

    public String getAgentUserInput() {
        if (isAgentIDsSelected())
            return idAgentTextField.getText();

        return percentageAgentTextField.getText();
    }

    private void createUIComponents() {
        idAgentRadioButton = new JRadioButton();
        percentageAgentRadioButton = new JRadioButton();

        buttonGroup = new ButtonGroup();
        buttonGroup.add(idAgentRadioButton);
        buttonGroup.add(percentageAgentRadioButton);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(9, 2, new Insets(10, 10, 10, 10), -1, -1));
        MainPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(8, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Bestimme die Agenten, die dieses Startkapital haben sollen...");
        panel1.add(label1, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        idAgentRadioButton.setSelected(true);
        idAgentRadioButton.setText("Wähle Agenten nach ihren IDs");
        panel1.add(idAgentRadioButton, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        idLabel = new JLabel();
        idLabel.setText("IDs:");
        panel1.add(idLabel, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        percentageAgentRadioButton.setText("Wähle Agenten nach prozentualem Anteil");
        panel1.add(percentageAgentRadioButton, new GridConstraints(6, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        percentageLabel = new JLabel();
        percentageLabel.setEnabled(false);
        percentageLabel.setText("Anteil:");
        panel1.add(percentageLabel, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        percentageAgentTextField = new JFormattedTextField();
        percentageAgentTextField.setEnabled(false);
        panel1.add(percentageAgentTextField, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Wähle ein Startkapital...");
        panel1.add(label2, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Startkapital: ");
        panel1.add(label3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        startCapitalTextField = new JFormattedTextField();
        panel1.add(startCapitalTextField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        idAgentTextField = new JFormattedTextField();
        panel1.add(idAgentTextField, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(-1, 20), null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }
}
