package de.sswis.view.CustomComponents.ResultTabs;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;

import javax.swing.*;
import java.awt.*;

public class CompareTab {

    private JPanel MainPanel;
    private JScrollPane differenceScrollPane;
    private JScrollPane averageScrollPane;


    public void setaverageChart(JFreeChart chart) {
        ChartPanel chartPanel = new ChartPanel(chart);
        averageScrollPane.setViewportView(chartPanel);
    }


    public void setDifferenceCharts(JFreeChart chart) {
        ChartPanel chartPanel = new ChartPanel(chart);
        averageScrollPane.setViewportView(chartPanel);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JSplitPane splitPane1 = new JSplitPane();
        splitPane1.setOrientation(1);
        MainPanel.add(splitPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        averageScrollPane = new JScrollPane();
        splitPane1.setLeftComponent(averageScrollPane);
        averageScrollPane.setBorder(BorderFactory.createTitledBorder("Durchschnitt"));
        differenceScrollPane = new JScrollPane();
        splitPane1.setRightComponent(differenceScrollPane);
        differenceScrollPane.setBorder(BorderFactory.createTitledBorder("Abweichung"));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }
}
