package de.sswis.view;

import com.intellij.uiDesigner.core.GridLayoutManager;
import de.sswis.view.AbstractManageConfigurationsView;
import de.sswis.view.model.VMConfiguration;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.List;

/**
 * Ein Fenster zum Verwalten von Konfigurationen.
 *
 * @author Sophie Bräuniger
 */
public class ManageConfigurationsView implements AbstractManageConfigurationsView {

    private List<VMConfiguration> vmConfigurations;
    private JPanel ButtonPanel;
    private JButton saveAndQuitButton;
    private JButton cancelButton;
    private JTabbedPane ConfigurationsPane;
    private JLabel descriptionLabel;
    private JTextPane textPane1;
    private JButton deleteButton;
    private JLabel nameLabel;
    private JButton editButton;
    private JButton newConfigButton;
    private JPanel MainPanel;


    @Override
    public void addConfiguration(VMConfiguration configuration) {

    }

    @Override
    public void removeConfiguration(String configName) {

    }

    @Override
    public void addNewConfigurationButtonActionlistener(ActionListener listener) {

    }

    @Override
    public void addEditConfigurationButtonActionlistener(ActionListener listener) {

    }

    @Override
    public void addDeleteConfigurationButtonActionlistener(ActionListener listener) {

    }

    @Override
    public void addCancelButtonActionlistener(ActionListener listener) {

    }

    @Override
    public void addSaveQuitButtonActionlistener(ActionListener listener) {

    }

    @Override
    public void update() {

    }

    @Override
    public void show() {

    }

    @Override
    public void close() {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
