package de.sswis.view;

import com.intellij.uiDesigner.core.GridLayoutManager;
import de.sswis.view.model.VMConfiguration;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.List;

/**
 * Ein Fenster zum Anzeigen von Ergebnissen einer Mehrfachkonfiguration.
 *
 * @author Sophie Bräuniger
 */
public class ShowMultiResultView implements AbstractShowMultiResultView {

    private JFrame frame;

    private List<VMConfiguration> vmConfigurations;

    private JPanel MainPanel;
    private JRadioButton averageRadioButton1;
    private JRadioButton singleRadioButton1;
    private JFormattedTextField kTextField1;
    private JSlider xSlider1;
    private JLabel configNameLabel;
    private JButton compareButton;
    private JRadioButton averageRadioButton2;
    private JRadioButton averageRadioButton3;
    private JRadioButton singleRadioButton3;
    private JRadioButton singleRadioButton2;
    private JFormattedTextField kTextField2;
    private JFormattedTextField kTextField3;
    private JSlider xSlider2;
    private JSlider xSlider3;
    private JScrollPane graphicResultPane3;
    private JScrollPane graphicResultPane2;
    private JScrollPane graphicResultPane1;
    private JComboBox comboBox1;
    private JFormattedTextField formattedTextField1;


    private AbstractMainView parentView;


    @Override
    public void update() {

    }

    @Override
    public void show() {
        frame = new JFrame("Ergebnisse Mehrfachkonfiguration");
        frame.setContentPane(this.MainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

    }

    @Override
    public void close() {

    }

    @Override
    public void addCompareButtonActionlistener(ActionListener listener) {

    }
  
    @Override
    public void setParentView(AbstractView parentView) {
        this.parentView = (AbstractMainView) parentView;
    }

    @Override
    public AbstractMainView getParentView() {
        return this.parentView;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }
}
